/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: this file is normally auto-generated by `next dev`/`next build`.
// It's checked in here so `tsc --noEmit` and editors work before the
// first `npm run dev`. Do not edit by hand once Next.js regenerates it.
